package:
  name: auto-dotenv
  version: 1.1

build:
  noarch: generic
  number: 0

test:
  files:
    - .env
  commands:
    - test "$HELLO" == "WORLD"

about:
  home: https://github.com/conda-forge/auto-dotenv-feedstock
  summary: 'Automatically load environment variables from .env when activating a conda environment.'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apoorvkh
